#!/usr/local/bin/perl

my $svrDir = '/home/brenan/web_server';
my $webDir = '/home/brenan/community_site';
my $cmd = 'kill `pgrep node`';
my $r = `$cmd`;
`nohup node $svrDir/host.js $webDir/ >> $svrDir/logs/nohup.out&`;
print "Started.\n";